### ISSUE TITLE
导出的材质丢失了！而且只能是Revit的“着色”或者一致颜色吗？

### ISSUE THREAD

**Issue by weiyu666** [McCulloughRT/Revit2glTF#7]
导出在3Dview打开下窗户材质丢失了！
![微信截图_20200720105623](https://user-images.githubusercontent.com/22174508/87895366-d0218c80-ca77-11ea-895e-91337d9f9163.png)
而且只能是Revit的“着色”模式不能是真实模式吗？
![微信截图_20200720105744](https://user-images.githubusercontent.com/22174508/87895386-de6fa880-ca77-11ea-92b5-595d5bedb631.png)
下图是在revit下打开的：

 原数据：
[昆山市金华村农房设计.zip](https://github.com/McCulloughRT/Revit2glTF/files/4945246/default.zip)

**Comment by McCulloughRT** [comment]
@weiyu666 adding full compatibility with the Revit Material system (textures, etc...) is coming soon for this exporter, but for now only diffuse colors are exported. Specific to your question about windows: I just merged a PR that will maintain the transparency of such materials. Try re-compiling of the current master :) .

**Comment by weiyu666** [comment]
Okay, according to my observation, the rendering of revit should be based on PBR, after all, PBR has become standard now; Unfortunately, his API exporter can only export simple diffuse materials. The exported material properties are not many and do not meet the Disney principles of BRDF! No, thank you anyway~
